#!/bin/bash
water_base10=$(echo "ibase=5; $WATER" | bc)
stir_base10=$(echo "ibase=7; $STIR" | bc)
sum_base10=$((water_base10 + stir_stir_base10))
echo "obase=9; $sum_base10" | bc

chmod +x 103-water_and_stir

